vim.opt.nu = true
vim.opt.spell = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.incsearch = true
vim.opt.signcolumn = "yes"
vim.opt.scrolloff = 10
vim.opt.tags='./tags'
vim.opt.smartindent = true
vim.opt.wrap = false
vim.g.mapleader = " "
